[theme]
# 背景色を黄緑っぽい蛍光グリーン（カラーコード：#000000）にする
backgroundColor = "#000000"

# メインの文字色をすべて黒（カラーコード："#CCFF00"）にする
textColor = "#CCFF00"

# もしサイドバーなど（サブの背景）も色を変えたい場合は以下を設定（今回は白にしています）
secondaryBackgroundColor = "#696969"
